apiVersion: batch/v1
kind: Job
metadata:
  name: recommendation-system-migrate
spec:
  template:
    spec:
      containers:
        - name: recommedation-system-app
          image: llazzaro/web_applications_django
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "recommendation_system.production"
          envFrom:
            - configMapRef:
                name: recommendation-system-settings
            - secretRef:
                name: recommendation-system-secrets
      restartPolicy: Never
  backoffLimit: 4
