apiVersion: v1
kind: Service
metadata:
  name: recommendation-system-service
spec:
  type: NodePort
  selector:
    app: recommendation-system-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
